from osoba_s_kamarady import Osoba_s_kamarady

mirek = Osoba_s_kamarady("Mirek", 30)
leos = Osoba_s_kamarady("Leos", 30)
lukas = Osoba_s_kamarady("Lukas", 29)
matej = Osoba_s_kamarady("Matej", 40)

mirek.pridej_kamarada(leos)
lukas.pridej_kamarada(mirek)

print("Kamaradi Mirka: {}".format(mirek.kamaradi))
print("Kamaradi Leos: {}".format(leos.kamaradi))
print("Kamaradi Lukas: {}".format(lukas.kamaradi))
print("Kamaradi Matej: {}".format(matej.kamaradi))
print()
mirek.predstav_se()
print()
leos.predstav_se()
print()
lukas.predstav_se()
print()
matej.predstav_se()
print()
mirek.odstan_kamarada_pomoci_poradi(2)
print()
mirek.predstav_se()
print()
lukas.predstav_se()
print()
mirek.odstan_kamarada_pomoci_poradi(2)